---
- hosts: localhost
  gather_facts: yes 
  become: false 
  vars:
   gold_ami_id: "{{ lookup('env','aws_image_id') }}"
   current_region: "{{ lookup('env','source_region') }}"
   target_region: "{{ lookup('env','target_region') }}"
   copied_ami_name: "{{ lookup('env','ami_name') }}"
  tasks:
   - name: Copy ami into mulitple region 
     ec2_ami_copy:
         name: {{ copied_ami_name }}
         source_image_id: "{{ gold_ami_id }}"
         region: "{{ current_region }}"
         source_region: "{{ target_region }}"
         wait_timeout: 1200
         wait: yes
     tags: copy_ami_into_region

   - name: Copy Ami from one account to another account 
     command: aws ec2 modify-image-attribute --image-id "{{ gold_ami_id }}" --launch-permission "Add=[{UserId=$aws_account_id}]"
     tags: share_ami_ado
     register: share_ami
